import{initMenu}from'./menu.js';import{initGallery}from'./gallery.js';import{initMotion}from'./motion.js';import{initCup}from'./cup.js';import{venue}from'./config.js';
const header=document.querySelector('.site-header'),toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('#site-nav');
header.classList.add('nav-ready');toggle.hidden=false;
function closeNav(focus=false){header.classList.remove('nav-open');toggle.setAttribute('aria-expanded','false');document.body.classList.remove('locked');if(focus)toggle.focus();}
toggle.addEventListener('click',()=>{const open=!header.classList.contains('nav-open');header.classList.toggle('nav-open',open);toggle.setAttribute('aria-expanded',String(open));document.body.classList.toggle('locked',open);});
nav.addEventListener('click',e=>{if(e.target.closest('a'))closeNav();});
document.addEventListener('keydown',e=>{if(!header.classList.contains('nav-open'))return;if(e.key==='Escape')closeNav(true);if(e.key==='Tab'){const list=[toggle,...nav.querySelectorAll('a')],first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
matchMedia('(max-width:760px)').addEventListener('change',()=>closeNav());
export function renderVenue(config){const links=document.querySelector('.venue-links');links.replaceChildren();if(!config.confirmed)return;const address=document.querySelector('.venue-address');address.textContent=config.address||'Адрес уточняется';const add=(label,href)=>{const a=document.createElement('a');a.className='text-link';a.textContent=label;a.href=href;links.append(a);};if(config.coordinates&&config.coordinates.length===2&&config.coordinates.every(Number.isFinite)){const[lat,lon]=config.coordinates;if(Math.abs(lat)<=90&&Math.abs(lon)<=180)add('Построить маршрут','https://yandex.ru/maps/?rtext=~'+encodeURIComponent(lat+','+lon));}if(/^\+?[\d ()-]{7,20}$/.test(config.phone))add(config.phone,'tel:'+config.phone.replace(/[^+\d]/g,''));if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(config.email))add(config.email,'mailto:'+config.email);for(const s of config.social||[])try{const u=new URL(s.url);if(u.protocol==='https:')add(s.title,u.href);}catch{}}
renderVenue(venue);initMenu();initGallery();initMotion();initCup();document.documentElement.dataset.ready='true';

