import{motion}from'./motion.js';
export function initCup(){const host=document.querySelector('.cup-visual'),start=host.querySelector('.cup-start'),exit=host.querySelector('.cup-exit'),turn=host.querySelector('.cup-turn'),status=host.querySelector('.cup-status'),slot=host.querySelector('.cup-canvas'),mode=new URLSearchParams(location.search).get('scene')||'normal',coarse=matchMedia('(pointer:coarse), (max-width:760px)');
 let controller=null,pending=null,generation=0,visible=false,autoAttempted=false,timer=0,userStopped=false;
 start.hidden=false;window.__mokaScene={state:'poster',frames:0,mode};if(mode==='no-steam'||mode==='poster')host.querySelector('.steam').remove();
 function syncPause(){const paused=!visible||document.hidden||!motion.enabled;document.body.classList.toggle('hero-paused',paused);controller?.pause(paused);}
 function stop(message=''){generation++;clearTimeout(timer);pending?.abort();pending=null;controller?.dispose();controller=null;slot.replaceChildren();host.dataset.state='poster';start.hidden=false;exit.hidden=true;turn.hidden=true;status.textContent=message;window.__mokaScene.state='poster';}
 async function activate(){if(controller||pending)return;if(!motion.enabled){status.textContent='Движение отключено. Показан статичный вид.';return;}userStopped=false;const serial=++generation,abort=new AbortController();pending=abort;host.dataset.state='loading';window.__mokaScene.state='loading';status.textContent='Готовим чашку…';start.hidden=true;exit.hidden=false;
 try{const {createLiveCup}=await import('./three/live.js');if(abort.signal.aborted)return;const canvas=document.createElement('canvas');canvas.setAttribute('aria-label','Объёмная чашка MOKA');slot.append(canvas);const live=await createLiveCup(canvas,{light:mode==='light'||navigator.connection?.saveData,signal:abort.signal,onError:()=>{userStopped=true;stop('Показан статичный вид. 3D сейчас недоступно.');}});if(abort.signal.aborted||serial!==generation){live.dispose();return;}controller=live;pending=null;host.dataset.state='ready';window.__mokaScene.state='ready';status.textContent=coarse.matches?'Поверните чашку кнопками или касанием.':'Немного движения — за вашим курсором';turn.hidden=!coarse.matches;syncPause();}
 catch(e){if(abort.signal.aborted||serial!==generation)return;pending=null;userStopped=true;stop('Показан статичный вид. 3D сейчас недоступно.');}}
 start.addEventListener('click',activate);exit.addEventListener('click',()=>{userStopped=true;stop();start.focus({preventScroll:true});});turn.addEventListener('click',e=>{const b=e.target.closest('[data-turn]');if(b)controller?.turn(Number(b.dataset.turn));});
 const io=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;syncPause();if(visible&&!autoAttempted&&!coarse.matches&&!userStopped&&motion.enabled&&mode!=='poster'&&!navigator.connection?.saveData){autoAttempted=true;timer=setTimeout(()=>{if(visible&&!document.hidden)activate();},700);}}, {threshold:.15});io.observe(host);
 document.addEventListener('visibilitychange',syncPause);addEventListener('moka:motion',()=>{if(!motion.enabled)stop();syncPause();});coarse.addEventListener('change',()=>{turn.hidden=!controller||!coarse.matches;controller?.reset();});
 addEventListener('pagehide',()=>{stop();io.disconnect();},{once:true});return{activate,stop};
}

