export const menuItems = [
  {
    "id": "espresso",
    "category": "coffee",
    "title": "Эспрессо",
    "description": "Плотный и выразительный, с мягким послевкусием.",
    "portionLabel": "40 мл",
    "priceMinor": 19000,
    "currency": "RUB",
    "image": "assets/images/espresso-640.webp",
    "alt": "Эспрессо на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "americano",
    "category": "coffee",
    "title": "Американо",
    "description": "Чистый вкус эспрессо, раскрытый горячей водой.",
    "portionLabel": "200 мл",
    "priceMinor": 21000,
    "currency": "RUB",
    "image": "assets/images/americano-640.webp",
    "alt": "Американо на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "cappuccino",
    "category": "coffee",
    "title": "Капучино",
    "description": "Баланс эспрессо и молока под бархатистой пеной.",
    "portionLabel": "200 мл",
    "priceMinor": 26000,
    "currency": "RUB",
    "image": "assets/images/cappuccino-640.webp",
    "alt": "Капучино на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "flat-white",
    "category": "coffee",
    "title": "Флэт уайт",
    "description": "Двойной эспрессо и тонкий слой молочной пены.",
    "portionLabel": "180 мл",
    "priceMinor": 29000,
    "currency": "RUB",
    "image": "assets/images/flat-white-640.webp",
    "alt": "Флэт уайт на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "latte",
    "category": "coffee",
    "title": "Латте",
    "description": "Мягкий молочный кофе для неспешного утра.",
    "portionLabel": "300 мл",
    "priceMinor": 29000,
    "currency": "RUB",
    "image": "assets/images/latte-640.webp",
    "alt": "Латте на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "raf",
    "category": "coffee",
    "title": "Раф",
    "description": "Эспрессо, сливки и деликатная ванильная сладость.",
    "portionLabel": "300 мл",
    "priceMinor": 34000,
    "currency": "RUB",
    "image": "assets/images/raf-640.webp",
    "alt": "Раф на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "filter",
    "category": "coffee",
    "title": "Фильтр",
    "description": "Лёгкий чёрный кофе, заваренный через бумажный фильтр.",
    "portionLabel": "250 мл",
    "priceMinor": 24000,
    "currency": "RUB",
    "image": "assets/images/filter-640.webp",
    "alt": "Фильтр на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "matcha",
    "category": "not-coffee",
    "title": "Матча-латте",
    "description": "Зелёный чай матча и тёплое молоко.",
    "portionLabel": "250 мл",
    "priceMinor": 32000,
    "currency": "RUB",
    "image": "assets/images/matcha-640.webp",
    "alt": "Матча-латте на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "cocoa",
    "category": "not-coffee",
    "title": "Какао",
    "description": "Насыщенный шоколадный вкус и мягкое молоко.",
    "portionLabel": "250 мл",
    "priceMinor": 28000,
    "currency": "RUB",
    "image": "assets/images/cocoa-640.webp",
    "alt": "Какао на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "tea",
    "category": "not-coffee",
    "title": "Чай",
    "description": "Чашка горячего чая для спокойной паузы.",
    "portionLabel": "350 мл",
    "priceMinor": 22000,
    "currency": "RUB",
    "image": "assets/images/tea-640.webp",
    "alt": "Чай на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "croissant",
    "category": "pastry",
    "title": "Круассан",
    "description": "Слоёное тесто, сливочный вкус и хрустящая корочка.",
    "portionLabel": "70 г",
    "priceMinor": 23000,
    "currency": "RUB",
    "image": "assets/images/croissant-640.webp",
    "alt": "Круассан на светлой керамике",
    "demo": true,
    "available": true
  },
  {
    "id": "lemon-cake",
    "category": "pastry",
    "title": "Лимонный кекс",
    "description": "Нежный кекс с цитрусовой нотой и тонкой глазурью.",
    "portionLabel": "110 г",
    "priceMinor": 29000,
    "currency": "RUB",
    "image": "assets/images/lemon-cake-640.webp",
    "alt": "Лимонный кекс на светлой керамике",
    "demo": true,
    "available": true
  }
];

