import{menuItems}from'./menu-data.js';
export function initMenu(items=menuItems){
 const section=document.querySelector('#menu'),preview=section.querySelector('.menu-preview'),mobile=matchMedia('(max-width:760px), (pointer:coarse)');
 let category='coffee',selected='cappuccino',open='',ticket=0,timer=0;
 const tabs=[...section.querySelectorAll('.menu-tabs a')].map(a=>{const b=document.createElement('button');b.type='button';b.textContent=a.textContent;b.dataset.category=a.dataset.category;b.setAttribute('aria-controls','menu-'+b.dataset.category);a.replaceWith(b);b.addEventListener('click',()=>changeCategory(b.dataset.category));return b;});
 const choices=[...section.querySelectorAll('.menu-choice')].map(a=>{const b=document.createElement('button');b.type='button';b.className=a.className;b.innerHTML=a.innerHTML;a.replaceWith(b);const id=b.closest('.menu-item').dataset.id;b.addEventListener('click',()=>choose(id,true));b.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&!mobile.matches){clearTimeout(timer);timer=setTimeout(()=>choose(id,false),100);}});b.addEventListener('pointerleave',()=>clearTimeout(timer));b.addEventListener('focus',()=>{if(!mobile.matches)choose(id,false);});return b;});
 function sync(){choices.forEach(b=>{const id=b.closest('.menu-item').dataset.id;b.setAttribute('aria-pressed',String(id===selected));if(mobile.matches){b.setAttribute('aria-expanded',String(id===open));b.setAttribute('aria-controls','preview-'+id);}else{b.removeAttribute('aria-expanded');b.removeAttribute('aria-controls');}});}
 async function show(item,inline){const token=++ticket;document.querySelector('.inline-preview')?.remove();if(!item)return;let target=preview;
 if(inline){target=document.createElement('figure');target.className='inline-preview';target.id='preview-'+item.id;document.getElementById(item.id).append(target);}
 const image=new Image();image.alt=item.alt;image.src=item.image;image.decoding='async';const cap=document.createElement('figcaption');const title=document.createElement('h3');title.textContent=item.title;const desc=document.createElement('p');desc.textContent=item.description;if(!inline)cap.append(title);cap.append(desc);
 // Reserve the previous image until decoding, but never label it as a different item.
 try{await image.decode();if(token!==ticket)return;target.replaceChildren(image,cap);target.classList.remove('preview-enter');requestAnimationFrame(()=>{if(token===ticket)target.classList.add('preview-enter');});}
 catch{if(token!==ticket)return;const msg=document.createElement('p');msg.className='photo-error';msg.textContent='Фото временно недоступно';target.replaceChildren(msg,cap);}
 }
 function choose(id,clicked){const item=items.find(p=>p.id===id);if(!item)return;if(!mobile.matches&&selected===id&&category===item.category&&!preview.querySelector('.photo-error'))return;if(item.category!==category)changeCategory(item.category,id);selected=id;
 if(mobile.matches){if(!clicked){sync();return;}open=open===id?'':id;ticket++;document.querySelector('.inline-preview')?.remove();if(open)show(item,true);}else{open='';show(item,false);}sync();}
 function changeCategory(next,id){clearTimeout(timer);category=next;open='';ticket++;document.querySelector('.inline-preview')?.remove();tabs.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===next)));let active=items.filter(p=>p.category===next);section.querySelectorAll('.menu-group').forEach(g=>{g.hidden=g.dataset.category!==next;g.querySelectorAll('.menu-item').forEach(row=>row.hidden=!active.some(p=>p.id===row.dataset.id));});section.querySelector('.menu-empty').hidden=active.length>0;preview.hidden=!active.length;selected=id||active[0]?.id||'';if(!mobile.matches&&selected)show(items.find(p=>p.id===selected),false);sync();}
 choices.forEach(b=>{const item=items.find(p=>p.id===b.closest('.menu-item').dataset.id);if(!item)return;const price=b.querySelector('.price');b.classList.toggle('unknown-price',!Number.isFinite(item.priceMinor));price.classList.toggle('price-unknown',!Number.isFinite(item.priceMinor));price.textContent=Number.isFinite(item.priceMinor)?new Intl.NumberFormat('ru-RU',{style:'currency',currency:item.currency,maximumFractionDigits:0}).format(item.priceMinor/100):'Уточняется';if(!item.available){b.closest('.menu-item').classList.add('unavailable');const s=document.createElement('span');s.className='availability';s.textContent='Сегодня недоступно';b.after(s);}});
 section.classList.add('menu-enhanced');changeCategory('coffee','cappuccino');
 document.querySelectorAll('[data-menu-link]').forEach(a=>a.addEventListener('click',()=>{const id=a.dataset.menuLink;if(items.some(p=>p.id===id)){choose(id,false);if(mobile.matches){open=id;show(items.find(p=>p.id===id),true);sync();}}}));
 function hash(){const id=location.hash.slice(1);if(items.some(p=>p.id===id)){choose(id,false);requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({block:'center'}));}else if(id.startsWith('menu-')&&tabs.some(b=>b.dataset.category===id.slice(5)))changeCategory(id.slice(5));}
 addEventListener('hashchange',hash);hash();mobile.addEventListener('change',()=>{open='';ticket++;document.querySelector('.inline-preview')?.remove();if(!mobile.matches&&selected)show(items.find(p=>p.id===selected),false);sync();});
 return{choose,changeCategory};
}
