import {enabled,subscribe} from './controller.js';
// Let the static poster and controls paint before loading Three.js.
async function posterFirst(poster,signal,automatic){
 await poster.decode().catch(()=>{});if(signal.aborted)return;
 await new Promise(resolve=>{let a=0,b=0;const done=()=>{cancelAnimationFrame(a);cancelAnimationFrame(b);signal.removeEventListener('abort',done);resolve();};signal.addEventListener('abort',done,{once:true});a=requestAnimationFrame(()=>{b=requestAnimationFrame(done);});});
 if(signal.aborted||!automatic)return;
 await new Promise(resolve=>{let id;const idle=!!window.requestIdleCallback;const done=()=>{idle?cancelIdleCallback(id):clearTimeout(id);signal.removeEventListener('abort',done);resolve();};signal.addEventListener('abort',done,{once:true});id=idle?requestIdleCallback(done):setTimeout(done,0);});
}
const stats=window.VOID_KINETIC_STATS??={created:0,disposed:0,active:0,frames:0};let automaticShown=false;
export function initKinetic(){
 const host=document.querySelector('[data-kinetic]');if(!host)return()=>{};
 const visual=host.querySelector('.kinetic-visual'),poster=visual.querySelector('img'),status=host.querySelector('.kinetic-status'),play=host.querySelector('[data-kinetic-play]'),pause=host.querySelector('[data-kinetic-pause]');
 const weak=()=>navigator.connection?.saveData||(navigator.deviceMemory&&navigator.deviceMemory<=4)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4)||matchMedia('(pointer:coarse)').matches;
 let loadAbort=null,scene=null,dead=false,generation=0,loading=false,frame=0,last=0,elapsed=0,progress=1,playing=false,visible=false,phase=-1,userStatic=false,autoPending=host.dataset.auto==='true'&&!automaticShown,resizeObserver=null;const samples=[],intervals=[],times=[.04,.27,.56,1];let slow=0;
 function ui(message){const index=progress<.13?0:progress<.44?1:progress<.7?2:3;if(index!==phase){phase=index;host.querySelectorAll('[data-kinetic-step]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));}status.textContent=message??(playing?['Элементы','Сборка знака','Знак','Применение'][index]:progress===1?'Готовый результат':'Кадр остановлен');pause.textContent=playing?'Пауза':'Продолжить';pause.disabled=!scene||!enabled();play.textContent=scene?'Повторить сборку ↻':enabled()?'Включить 3D ↗':'Готовый результат';}
 function paint(){if(!scene||dead)return;const t=performance.now();scene.render(progress);samples.push(performance.now()-t);if(samples.length>1500)samples.shift();stats.frames++;}
 function halt(){cancelAnimationFrame(frame);frame=0;last=0;}
 function release(){generation++;loadAbort?.abort();loadAbort=null;loading=false;halt();playing=false;resizeObserver?.disconnect();resizeObserver=null;if(scene){scene.dispose();scene=null;stats.disposed++;stats.active--;}poster.hidden=false;}
 function staticFrame(index=3,message='Статичный вид'){release();progress=times[index];poster.src=`assets/images/kinetic/kinetic-${index}.png`;ui(message);}
 function tick(now){frame=0;if(dead||!scene||!playing||!visible||document.hidden)return;if(!enabled()){staticFrame(3,'Без движения');return;}if(!last)last=now;if(now-last>=1000/30-1){const dt=now-last;last=now;intervals.push(dt);if(intervals.length>1500)intervals.shift();elapsed+=dt;progress=Math.min(1,elapsed/10000);paint();if(samples.at(-1)>28||dt>85)slow++;else slow=Math.max(0,slow-1);if(slow>=12){userStatic=true;staticFrame(3,'Облегчённый режим / доступен повтор');return;}if(progress===1)playing=false;ui();}if(playing)frame=requestAnimationFrame(tick);}
 function schedule(){if(scene&&playing&&visible&&!document.hidden&&enabled()&&!frame){last=0;frame=requestAnimationFrame(tick);}}
 async function load(automatic=false){if(dead||loading||scene||!enabled())return;loading=true;loadAbort=new AbortController();const signal=loadAbort.signal;const token=++generation;status.textContent='Подготовка сцены…';try{await posterFirst(poster,signal,automatic);if(dead||signal.aborted||generation!==token||!enabled())return;if(automatic&&(!visible||document.hidden)){autoPending=true;return;}const {createScene}=await import('../three/kinetic-scene.js');if(dead||generation!==token||!enabled())return;const nextScene=await createScene(visual,{signal});if(dead||generation!==token||!enabled()){nextScene.dispose();return;}scene=nextScene;stats.created++;stats.active++;const currentScene=scene;scene.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(!dead&&scene===currentScene){userStatic=true;staticFrame(3,'Статичный вид / WebGL недоступен');}},{once:true});progress=0;elapsed=0;slow=0;playing=true;paint();poster.hidden=true;resizeObserver=new ResizeObserver(()=>{if(!scene||dead)return;scene.resize();if(visible&&!document.hidden)paint();});resizeObserver.observe(visual);if(automatic)automaticShown=true;ui();schedule();}catch{if(!dead&&generation===token){userStatic=true;staticFrame(3,'Статичный вид / 3D недоступно');}}finally{if(generation===token)loading=false;}}
 const click=e=>{if(e.target.closest('[data-kinetic-static]')){autoPending=false;userStatic=true;staticFrame();}if(e.target.closest('[data-kinetic-play]')){autoPending=false;if(!enabled()){staticFrame(3,'Без движения');return;}userStatic=false;if(scene){halt();progress=elapsed=0;playing=true;slow=0;ui();schedule();}else load();}if(e.target.closest('[data-kinetic-pause]')&&scene&&enabled()){playing=!playing;if(progress===1){progress=elapsed=0;}ui();if(playing)schedule();else halt();}const b=e.target.closest('[data-kinetic-step]');if(b){autoPending=false;playing=false;halt();progress=times[+b.dataset.kineticStep];elapsed=progress*10000;if(scene)paint();else poster.src=`assets/images/kinetic/kinetic-${b.dataset.kineticStep}.png`;ui('Выбранный кадр');}};
 host.addEventListener('click',click);
 const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible){if(autoPending&&!weak()&&enabled()&&!userStatic){autoPending=false;load(true);}else schedule();}else halt();},{threshold:.08});io.observe(visual);
 const visibility=()=>{if(document.hidden)halt();else schedule();};document.addEventListener('visibilitychange',visibility);
 const unsub=subscribe(on=>{if(!on){autoPending=false;staticFrame(3,'Без движения');}else ui(weak()?'Статичный режим / 3D по нажатию':'Готовый результат');});
 ui(!enabled()?'Без движения':weak()?'Статичный режим / 3D по нажатию':'Готовый результат');
 host._debug={get scene(){return scene},get active(){return !!frame},get playing(){return playing},get progress(){return progress},get frames(){return scene?.info.frames??0},get info(){return scene?.info??null},get samples(){return samples},get intervals(){return intervals},get visible(){return visible},get loading(){return loading},static:staticFrame};
 return()=>{if(dead)return;dead=true;release();host.removeEventListener('click',click);io.disconnect();unsub();document.removeEventListener('visibilitychange',visibility);};
}
