import * as T from '../../assets/vendor/three/three.module.js';import{GLTFLoader}from'../../assets/vendor/three/GLTFLoader.js';import{createStudio,presets}from'./studio.js';import{compileCancellable}from'./compile.js';
export async function createLive(frame,id,onFailure,signal){const own=new AbortController(),opts={signal:own.signal};let studio=null,canvas=null,raf=0,disposed=false,visible=true,animation=null,drag=null,renderCount=0,angleX=0,angleY=0,currentExplode=0;const materials=new Set(),geometries=new Set();
 function dispose(){if(disposed)return;disposed=true;own.abort();cancelAnimationFrame(raf);resize?.disconnect();studio?.dispose();if(!studio){materials.forEach(m=>m.dispose());geometries.forEach(g=>g.dispose());}canvas?.remove();signal?.removeEventListener('abort',dispose);}
 signal?.addEventListener('abort',dispose,{once:true});let resize;
 try{const response=await fetch(new URL('../../assets/models/'+id+'.glb',import.meta.url),{signal:signal||own.signal});if(!response.ok)throw Error('Model HTTP '+response.status);const buffer=await response.arrayBuffer();if(disposed)throw new DOMException('Cancelled','AbortError');const gltf=await new GLTFLoader().parseAsync(buffer,'');const model=gltf.scene;model.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)materials.add(o.material);});if(disposed){materials.forEach(m=>m.dispose());geometries.forEach(g=>g.dispose());throw new DOMException('Cancelled','AbortError');}canvas=document.createElement('canvas');canvas.setAttribute('aria-label','Интерактивная архитектурная модель');frame.append(canvas);studio=createStudio(canvas,model,id);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();dispose();onFailure();},opts);resize=new ResizeObserver(entries=>{if(disposed)return;const {width,height}=entries[0].contentRect;studio.resize(width,height,Math.min(devicePixelRatio,1.5));request();});resize.observe(frame);studio.resize(frame.clientWidth,frame.clientHeight,Math.min(devicePixelRatio,1.5));await compileCancellable(studio.renderer,studio.scene,studio.camera,own.signal);if(disposed)throw new DOMException('Cancelled','AbortError');
 const target=new T.Vector3(...presets[id].perspective.target),basePosition=new T.Vector3(...presets[id].perspective.position);
 function draw(){if(disposed||!visible||document.hidden)return;studio.render();renderCount++;canvas.dataset.frames=String(renderCount);}
 function tick(now){raf=0;if(disposed||!visible||document.hidden)return;if(animation){const p=Math.min(1,(now-animation.start)/animation.duration),ease=p*p*(3-2*p);animation.apply(ease);if(p===1)animation=null;}draw();if(animation)raf=requestAnimationFrame(tick);}
 function request(){if(!raf&&!disposed&&visible&&!document.hidden)raf=requestAnimationFrame(tick);}
 function cancelAnimation(){animation=null;cancelAnimationFrame(raf);raf=0;}
 function tween(apply,duration=800){cancelAnimation();animation={start:performance.now(),duration,apply};request();}
 function view(name){cancelAnimation();studio.view(name);target.fromArray(presets[id][name].target);basePosition.copy(studio.camera.position);angleX=angleY=0;request();}
 function stage(name){studio.stage(name);request();}
 function explode(value,animate=false){const from=currentExplode;currentExplode=value;if(animate)tween(p=>studio.explode(from+(value-from)*p));else{cancelAnimation();studio.explode(value);request();}}
 function highlight(name){studio.highlight(name);request();}
 function reset(){cancelAnimation();studio.model.rotation.set(0,0,0);currentExplode=0;studio.explode(0);studio.stage('render');studio.highlight('');view('perspective');}
 function story(p,smooth=false){const from=studio.camera.position.clone(),fromTarget=target.clone();cancelAnimation();const top=presets[id].top,perspective=presets[id].perspective,detail=presets[id].detail;let a=top,b=perspective,t=Math.max(0,Math.min(1,(p-.12)/.38));if(p>.7){a=perspective;b=detail;t=Math.min(1,(p-.7)/.3);}t=t*t*(3-2*t);studio.camera.position.fromArray(a.position).lerp(new T.Vector3(...b.position),t);target.fromArray(a.target).lerp(new T.Vector3(...b.target),t);studio.camera.lookAt(target);studio.stage(p<.2?'sketch':p<.48?'model':'render');basePosition.copy(studio.camera.position);angleX=angleY=0;if(smooth){const to=studio.camera.position.clone(),toTarget=target.clone();tween(t=>{studio.camera.position.copy(from).lerp(to,t);target.copy(fromTarget).lerp(toTarget,t);studio.camera.lookAt(target);},400);}else request();}
 function orient(){const offset=basePosition.clone().sub(target),spherical=new T.Spherical().setFromVector3(offset);spherical.theta+=angleY;spherical.phi=Math.max(.08,Math.min(Math.PI/2-.03,spherical.phi+angleX));studio.camera.position.copy(target).add(new T.Vector3().setFromSpherical(spherical));studio.camera.lookAt(target);request();}
 canvas.addEventListener('pointerdown',e=>{if(!frame.classList.contains('manual'))return;cancelAnimation();drag={x:e.clientX,y:e.clientY,ax:angleX,ay:angleY};canvas.setPointerCapture(e.pointerId);},opts);
 canvas.addEventListener('pointermove',e=>{if(!drag)return;angleY=Math.max(-1.1,Math.min(1.1,drag.ay+(e.clientX-drag.x)*.005));angleX=Math.max(-.35,Math.min(.35,drag.ax+(e.clientY-drag.y)*.003));orient();},opts);canvas.addEventListener('pointerup',()=>drag=null,opts);canvas.addEventListener('pointercancel',()=>drag=null,opts);
 function setVisible(value){visible=value;if(!value){cancelAnimationFrame(raf);raf=0;if(animation){animation.apply(1);animation=null;}}else request();}
 draw();const api={dispose,view,stage,explode,highlight,reset,story,setVisible,get stats(){return{frames:renderCount,calls:studio.renderer.info.render.calls,triangles:studio.renderer.info.render.triangles,geometries:studio.renderer.info.memory.geometries,textures:studio.renderer.info.memory.textures,width:canvas.width,height:canvas.height};}};frame.axisScene=api;own.signal.addEventListener('abort',()=>delete frame.axisScene,{once:true});return api;
 }catch(error){dispose();throw error;}}
