M.add=(id,quiet=false)=>{if(!M.state.items.some(i=>i.id===id))M.state.items.push({id,volume:''});M.save();M.selectionBar();if(!quiet)M.toast('Материал добавлен в запрос');};
M.selectionBar=()=>{document.querySelectorAll('[data-selection-count]').forEach(n=>n.textContent=M.state.items.length);document.querySelectorAll('.selection-bar').forEach(n=>n.hidden=!M.state.items.length);};
M.field=(label,name,options={})=>`<label class="field ${options.wide?'wide':''}">${label}${options.area?`<textarea name="${name}" rows="3" maxlength="2000">${M.esc(M.draft[name])}</textarea>`:`<input name="${name}" type="${options.type||'text'}" ${options.required?'required':''} ${options.mode?'inputmode="'+options.mode+'"':''} value="${M.esc(M.draft[name])}" ${options.placeholder?'placeholder="'+options.placeholder+'"':''} ${options.type==='date'?'min="'+new Date().toLocaleDateString('en-CA')+'"':''} maxlength="200">`}<span class="error" data-error="${name}"></span></label>`;
M.quoteItems=()=>M.state.items.map(i=>{const p=M.products.find(p=>p.id===i.id);return `<div class="quote-item"><div><strong>${p.name}</strong><small>${p.b||'Параметры уточняются'} / По запросу</small></div><label class="field">Объём, м³<input inputmode="decimal" data-volume="${i.id}" ${M.draft.unknown?'disabled':''} value="${M.esc(i.volume)}" placeholder="Уточняется" aria-label="Объём ${p.name}"><span class="error"></span></label><button type="button" class="icon-button" data-remove="${i.id}" aria-label="Убрать ${p.name}">×</button></div>`;}).join('');
M.quoteForm=(full=false)=>`<form class="quote-form" novalidate><p class="small">Сформируйте запрос. В этом концепте данные не отправляются.${M.source?'<br>Контекст: '+M.esc(M.source):''}</p><div class="quote-items">${M.quoteItems()}</div><div class="form-grid">${M.field('Потребность / тема','need',{wide:true,placeholder:'Материал, услуга или вопрос'})}${M.field('Имя *','name',{required:true,placeholder:'Как к вам обращаться'})}${M.field('Телефон или email *','contact',{required:true,placeholder:'Для демонстрации — вымышленные данные'})}</div><details class="quote-details" ${full?'open':''}><summary>Добавить детали объекта</summary><div class="form-grid">${M.field('Компания','company')}${M.field('Желаемая дата','date',{type:'date'})}${M.field('Адрес / район объекта','address',{wide:true})}${M.field('График / этапы поставки','schedule',{wide:true})}</div><fieldset><legend>Услуги</legend><div class="service-choices">${M.services.map(s=>`<label class="check"><input type="checkbox" name="services" value="${s.id}" ${M.state.services.includes(s.id)?'checked':''}>${s.name}</label>`).join('')}</div></fieldset><div class="pump-fields form-grid" ${M.state.services.includes('pump')?'':'hidden'}>${M.field('Высота подачи, если известна','height')}${M.field('Дальность подачи, если известна','distance')}${M.field('Подъезд и площадка','access',{wide:true})}</div><label class="check"><input name="unknown" type="checkbox" ${M.draft.unknown?'checked':''}>Объём / параметры нужно уточнить</label><div class="form-grid">${M.field('Требования, тема контроля, комментарий','comment',{area:true,wide:true})}<label class="field wide">Спецификация (необязательно)<input name="attachments" type="file" multiple accept=".pdf,.docx,.xlsx"><span class="small">До 2 файлов, каждый до 10 МБ. PDF, DOCX, XLSX. Только имена и размеры, без отправки.</span><span data-files>${M.draft.files.map(f=>M.esc(f.name)+' · '+Math.ceil(f.size/1024)+' КБ').join('<br>')}</span><span class="error" data-error="attachments"></span></label></div></details><p class="form-error error" role="alert"></p><button class="button" type="submit">Сформировать демозапрос <span aria-hidden="true">↗</span></button></form>`;
M.capture=form=>{if(!form)return;for(const key of Object.keys(M.draft)){const el=form.elements[key];if(el&&key!=='files')M.draft[key]=el.type==='checkbox'?el.checked:el.value;}};
M.openQuote=(source='',service='',id='')=>{M.capture(document.querySelector('main .quote-form'));if(id)M.add(id,true);if(service&&!M.state.services.includes(service))M.state.services.push(service);M.save();M.source=source;if(!M.draft.need&&/документ/i.test(source))M.draft.need=source;M.returnFocus=document.activeElement;const d=document.querySelector('#quote-dialog');document.querySelector('#dialog-content').innerHTML=M.quoteForm(true);if(!d.open)d.showModal();};
M.closeQuote=()=>{M.capture(document.querySelector('#dialog-content .quote-form'));const d=document.querySelector('#quote-dialog');d.close();const inline=document.querySelector('main .inline-quote');if(inline)inline.innerHTML=M.quoteForm();M.returnFocus?.isConnected&&M.returnFocus.focus();};
M.volume=v=>{if(!String(v).trim())return null;const text=String(v).trim().replace(',','.');return /^\d+(\.\d+)?$/.test(text)?Number(text):NaN;};
M.submitQuote=form=>{
 M.capture(form);form.querySelectorAll('.error').forEach(n=>n.textContent='');let invalid=false;
 const error=(name,text)=>{const n=form.querySelector('[data-error="'+name+'"]');if(n)n.textContent=text;invalid=true;form.elements[name]?.setAttribute('aria-invalid','true');};
 form.querySelectorAll('[aria-invalid]').forEach(n=>n.removeAttribute('aria-invalid'));
 if(!M.draft.name.trim())error('name','Укажите имя.');
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(M.draft.contact)&&!(/^\+?[\d\s()\-]{10,22}$/.test(M.draft.contact)&&M.draft.contact.replace(/\D/g,'').length>=10))error('contact','Введите email или телефон (не менее 10 цифр).');
 if(!M.draft.need.trim()&&!M.state.items.length&&!M.state.services.length)error('need','Укажите материал, услугу или тему.');
 form.querySelectorAll('[data-volume]').forEach(el=>{const n=M.volume(el.value);if(!M.draft.unknown&&el.value.trim()&&(!Number.isFinite(n)||n<=0)){el.nextElementSibling.textContent='Положительный объём, например 12,5';el.setAttribute('aria-invalid','true');invalid=true;}});
 if(M.attachmentError)error('attachments',M.attachmentError);
 if(invalid){form.querySelector('.form-error').textContent='Проверьте отмеченные поля. Введённые данные сохранены в этой вкладке.';form.querySelector('[aria-invalid]')?.focus();return;}
 const summary={source:M.source||'Форма на странице',need:M.draft.need,materials:M.state.items.map(i=>({name:M.products.find(p=>p.id===i.id).name,volume:M.draft.unknown?null:M.volume(i.volume)})),services:M.state.services.map(id=>M.services.find(s=>s.id===id).name),...M.draft};M.lastSummary=summary;
 form.innerHTML=`<div class="success"><span class="eyebrow">ЗАПРОС / СФОРМИРОВАН</span><h2>Демозаявка сформирована.</h2><p>Данные никуда не отправлены. Стоимость и график не подтверждены.</p><dl><dt>Потребность</dt><dd>${M.esc(summary.need)||'По выбранным позициям'}</dd><dt>Материалы</dt><dd>${summary.materials.map(i=>M.esc(i.name)+' — '+(i.volume===null?'объём уточняется':i.volume+' м³')).join('<br>')||'Требуется уточнение'}</dd><dt>Услуги</dt><dd>${M.esc(summary.services.join(', '))||'Не выбраны'}</dd><dt>Объект / дата</dt><dd>${M.esc(summary.address||'Уточняется')} / ${M.esc(summary.date||'Уточняется')}</dd><dt>Контакт</dt><dd>${M.esc(summary.name)} · ${M.esc(summary.contact)}</dd><dt>Файлы</dt><dd>${summary.files.map(f=>M.esc(f.name)).join(', ')||'Не выбраны'}</dd></dl><button type="button" class="button secondary" data-edit-quote>Изменить запрос</button></div>`;
};
document.addEventListener('input',e=>{const form=e.target.closest('.quote-form');if(!form)return;M.capture(form);if(e.target.matches('[data-volume]')){const i=M.state.items.find(i=>i.id===e.target.dataset.volume);i.volume=e.target.value;M.save();}});
document.addEventListener('change',e=>{const f=e.target.closest('.quote-form');if(!f)return;if(e.target.name==='unknown'){f.querySelectorAll('[data-volume]').forEach(n=>n.disabled=e.target.checked);}if(e.target.name==='services'){M.state.services=[...f.querySelectorAll('[name=services]:checked')].map(n=>n.value);M.save();f.querySelector('.pump-fields').hidden=!M.state.services.includes('pump');}if(e.target.name==='attachments'){const files=[...e.target.files];M.attachmentError=files.length>2?'Допускается не более двух файлов.':files.some(f=>f.size>10*1024*1024)?'Каждый файл должен быть не более 10 МБ.':files.some(f=>!(/\.(pdf|docx|xlsx)$/i.test(f.name)))?'Допустимые форматы: PDF, DOCX, XLSX.':'';M.draft.files=M.attachmentError?[]:files.map(({name,size})=>({name,size}));f.querySelector('[data-error=attachments]').textContent=M.attachmentError;f.querySelector('[data-files]').textContent=M.draft.files.map(f=>f.name+' · '+Math.ceil(f.size/1024)+' КБ').join(', ');}});
document.addEventListener('submit',e=>{if(e.target.matches('.quote-form')){e.preventDefault();M.submitQuote(e.target);}});
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.hasAttribute('data-quote'))M.openQuote(el.dataset.quote,el.dataset.service,el.dataset.product);if(el.hasAttribute('data-close'))M.closeQuote();if(el.dataset.remove){M.state.items=M.state.items.filter(i=>i.id!==el.dataset.remove);M.save();el.closest('.quote-item').remove();M.selectionBar();}if(el.hasAttribute('data-edit-quote')){el.closest('.quote-form').outerHTML=M.quoteForm(true);}if(el.dataset.add)M.add(el.dataset.add);});
document.querySelector('#quote-dialog').addEventListener('cancel',e=>{e.preventDefault();M.closeQuote();});
