TQ.icon=(name,extra='')=>`<img class="icon ${extra}" src="assets/icons/${name}.svg" alt="" aria-hidden="true">`;
TQ.button=(label,action,extra='')=>`<button class="btn" data-action="${action}" ${extra}>${label}</button>`;
TQ.crumbs=items=>`<nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="#/">Главная</a>${items.map(([text,url])=>`<span aria-hidden="true">/</span>${url?`<a href="${url}">${TQ.esc(text)}</a>`:`<span aria-current="page">${TQ.esc(text)}</span>`}`).join('')}</nav>`;
TQ.heading=(title,subtitle='')=>`<div class="page-title"><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div>`;
TQ.empty=(title,copy,label='Открыть каталог',url='#/catalog',icon='package')=>`<div class="empty">${TQ.icon(icon)}<h2>${title}</h2><p>${copy}</p><a class="btn" href="${url}">${label}</a></div>`;
TQ.compatMarkup=(p,large=false)=>{const state=TQ.compat(p);const text={unknown:'Выберите автомобиль',check:'Совместимость не проверена',match:'Подходит к вашему автомобилю',mismatch:'Не подходит к вашему автомобилю'}[state];return `<div class="compatibility ${state} ${large?'large':''}">${large?`<strong>${state==='match'?'✓':state==='mismatch'?'!':'ⓘ'} ${text}</strong><p>${TQ.car()?`${TQ.car().make} ${TQ.car().badge} · ${TQ.car().year} · ${TQ.car().engine}`:'Укажите автомобиль, чтобы проверить совместимость.'}</p>${state==='unknown'?'<button class="text-btn" data-action="car-modal">Выбрать автомобиль →</button>':''}`:`<span>${state==='match'?'✓':state==='mismatch'?'!':'ⓘ'}</span> ${text}`}</div>`;};
TQ.card=p=>`<article class="product-card"><button class="icon-btn favorite ${TQ.state.favorites.includes(p.id)?'active':''}" data-action="favorite" data-id="${p.id}" aria-label="Избранное: ${p.name}" aria-pressed="${TQ.state.favorites.includes(p.id)}">${TQ.icon('heart')}</button><a class="product-photo" href="#/product?id=${p.id}" aria-label="${p.brand} ${p.name}"><img src="assets/products/${p.image}.webp" alt="${p.name}, иллюстрация" loading="lazy" width="250" height="180"></a><div class="brand">${p.brand}</div><a class="product-name" href="#/product?id=${p.id}">${p.name}</a><div class="sku">Артикул: ${p.sku}</div><p class="parameters">${p.params}</p>${TQ.compatMarkup(p)}<div class="price">${TQ.money(p.price)} <small>/ ${p.unit}</small></div><div class="stock ${p.stock?'':'unavailable'}">${p.stock?'В наличии':'Под заказ'}</div><div class="delivery">${TQ.deliveryText(p)}</div><button class="btn ${TQ.state.cart.some(x=>x.id===p.id)?'added':''}" data-action="${p.stock?'add-cart':'request-stock'}" data-id="${p.id}">${p.stock?(TQ.state.cart.some(x=>x.id===p.id)?'В корзине · ещё':'В корзину'):'Уточнить срок'}</button></article>`;
TQ.productGrid=products=>`<div class="product-grid">${products.map(TQ.card).join('')}</div>`;
TQ.deliveryText=p=>`Доставка ${TQ.state.city==='Москва'?'от '+p.days:'от '+(p.days+2)} ${p.days===1&&TQ.state.city==='Москва'?'дня':'дней'}`;
TQ.brandLogo=b=>b.slug==='ate'?'<span class="brand-fallback" aria-label="ATE">ATE</span>':`<img class="brand-logo" src="assets/logos/${b.slug}-display.png" alt="${b.name}" width="160" height="48">`;
TQ.brandStrip=()=>{const group=duplicate=>`<div class="brand-marquee-group" ${duplicate?'aria-hidden="true" inert':''}>${TQ.brands.slice(0,6).map(b=>`<a class="brand-tile" href="${TQ.route('category',{brand:b.name})}" aria-label="Запчасти ${b.name}"${duplicate?' tabindex="-1"':''}>${TQ.brandLogo(b)}</a>`).join('')}</div>`;return `<div class="brand-strip" aria-label="Производители автокомпонентов"><div class="brand-marquee-track">${group(false)}${group(true)}</div></div>`;};
TQ.help=()=>`<section class="help-banner"><div><h2>Не нашли нужную деталь?</h2><p>Начните с VIN — поможем разобраться в совместимости и аналогах.</p></div><a class="btn" href="#/search?mode=vin">Подобрать по VIN ${TQ.icon('arrow-right','white')}</a></section>`;
TQ.recent=()=>`<section class="section"><div class="section-head"><h2>Недавно просмотренные</h2><span class="small muted">${TQ.state.viewed.length?'Ваша история':'Вы смотрели или могли пропустить'}</span></div>${TQ.productGrid((TQ.state.viewed.length?TQ.state.viewed.map(TQ.product):[TQ.products[0],TQ.products[2],TQ.products[3],TQ.products[4]]).slice(0,4))}</section>`;
TQ.benefits=()=>`<div class="benefits">${[['shield-check','Проверка совместимости','Выбранный автомобиль всегда рядом с деталью.'],['truck','Понятные сроки','Стоимость и срок получения видны до оформления.'],['file-check','Гарантия и возврат','Условия и порядок обращения — в одном разделе.'],['headphones','Помощь в подборе','Если есть сомнения, начните с запроса по VIN.']].map(([i,t,p])=>`<div class="benefit">${TQ.icon(i)}<h3>${t}</h3><p>${p}</p></div>`).join('')}</div>`;
TQ.renderHeader=()=>{
 const checkout=TQ.current?.page==='checkout';
 document.getElementById('service').innerHTML=`<div class="service-bar"><div class="container"><button data-action="city" class="row" style="gap:6px">${TQ.icon('map-pin')} ${TQ.state.city} <span>⌄</span></button><nav><a href="#/delivery">Доставка и оплата</a><a href="#/warranty">Гарантия и возврат</a><a href="#/contacts">Контакты</a><a href="#/contacts">Поддержка</a></nav></div></div>`;
 document.getElementById('header').innerHTML=`<div class="container header-inner"><a href="#/" class="logo" aria-label="TORQ, главная">TORQ<span>▪</span></a>${checkout?`<a href="#/cart" class="link">← Вернуться в корзину</a><div class="grow"></div><span class="small muted">Оформление заказа</span><a class="link" href="#/contacts">Помощь</a>`:`<button class="btn catalog-btn" data-action="catalog-menu" aria-expanded="false" aria-controls="mega-menu">${TQ.icon('menu','white')} Каталог</button><div class="global-search"><form id="global-search" role="search"><label for="global-query" class="sr-only">Поиск по артикулу, OEM или названию</label>${TQ.icon('search')}<input id="global-query" type="search" placeholder="Артикул, OEM или название детали" value="${TQ.esc(TQ.state.search)}" autocomplete="off"><button class="search-submit" aria-label="Найти">${TQ.icon('arrow-right')}</button></form><div id="suggestions" class="suggestions" hidden></div></div><nav class="header-actions" aria-label="Личный кабинет"><a class="header-action" href="#/garage">${TQ.icon('car')}${TQ.car()?'<span class="garage-dot"></span>':''}<span>Гараж</span></a><a class="header-action" href="#/garage?tab=favorites">${TQ.icon('heart')}<span>Избранное</span>${TQ.state.favorites.length?`<b class="badge">${TQ.state.favorites.length}</b>`:''}</a><a class="header-action" href="#/garage?tab=profile">${TQ.icon('user')}<span>Профиль</span></a><a class="header-action cart" href="#/cart">${TQ.icon('shopping-bag')}<span>Корзина · <b>${TQ.money(TQ.subtotal())}</b></span>${TQ.cartCount()?`<b class="badge">${TQ.cartCount()}</b>`:''}</a></nav>`}</div>${checkout?'':'<div id="mega-menu" class="mega-menu" hidden></div>'}`;
};
TQ.refreshHeader=()=>{
 const city=document.querySelector('#service [data-action="city"]');
 if(city)city.innerHTML=`${TQ.icon('map-pin')} ${TQ.esc(TQ.state.city)} <span>⌄</span>`;
 const cart=document.querySelector('.header-action.cart');
 if(cart){TQ.moneyMotion(cart.querySelector('span b'),TQ.subtotal());TQ.updateBadge(cart,TQ.cartCount());}
 const favorites=document.querySelector('.header-action[href="#/garage?tab=favorites"]');
 if(favorites)TQ.updateBadge(favorites,TQ.state.favorites.length);
};
TQ.renderFooter=()=>{document.getElementById('footer').innerHTML=`<div class="container"><div class="footer-grid"><div><a href="#/" class="logo">TORQ<span>▪</span></a><p>Запчасти для вашего автомобиля.<br>Точный подбор. Понятный выбор.</p></div><div><h3>Каталог</h3><nav><a href="#/category?cat=suspension">Подвеска</a><a href="#/category?cat=brakes">Тормозная система</a><a href="#/category?cat=engine">Двигатель</a><a href="#/catalog">Все категории →</a></nav></div><div><h3>Покупателям</h3><nav><a href="#/delivery">Доставка и оплата</a><a href="#/warranty">Гарантия и возврат</a><a href="#/search?mode=vin">Подбор по VIN</a><a href="#/garage">Мой гараж</a></nav></div><div><h3>Компания</h3><nav><a href="#/about">О TORQ</a><a href="#/brands">Бренды</a><a href="#/contacts">Контакты</a></nav><p style="margin-top:16px">Пн–Пт, 09:00–19:00</p></div></div><div class="footer-bottom"><span>© 2026 TORQ</span><span>Точность в каждой детали.</span><button data-action="privacy">Конфиденциальность</button></div></div>`;};
TQ.mega=(category='suspension')=>{const c=TQ.category(category);document.getElementById('mega-menu').innerHTML=`<div class="container mega-inner"><div class="mega-groups">${TQ.categories.map(x=>`<button class="mega-group ${x.id===c.id?'active':''}" data-action="mega-group" data-cat="${x.id}">${x.name}<span>›</span></button>`).join('')}</div><div><h2>${c.name}</h2><div class="mega-subcategories">${c.sub.map(s=>`<a href="${TQ.route('category',{cat:c.id,sub:s})}">${s}</a>`).join('')}</div><div class="mega-bottom"><a href="#/catalog" class="link">Весь каталог →</a><a href="#/brands" class="link">Все бренды →</a><a href="#/search?mode=vin" class="link">Подбор по VIN →</a></div></div></div>`;};
TQ.modal=(title,html)=>{const d=document.getElementById('modal');d.innerHTML=`<div class="modal-head"><h2 id="modal-title">${title}</h2><button class="icon-btn" data-action="close-modal" aria-label="Закрыть окно">${TQ.icon('x')}</button></div>${html}`;if(!d.open)d.showModal();};
TQ.closeModal=()=>{const d=document.getElementById('modal');d.getAnimations().forEach(a=>a.cancel());d.classList.remove('closing');d.close();};
TQ.toast=(text,action='')=>{clearTimeout(TQ.toastTimer);const t=document.getElementById('toast');t.innerHTML=`<span>${TQ.esc(text)}</span>${action}`;t.classList.add('show');TQ.toastTimer=setTimeout(()=>t.classList.remove('show'),5000);};
