import {services} from './data.js';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const arrow='<span aria-hidden="true">↗</span>';
export const button=(text,href,primary=false,magnet=false)=>'<a class="button '+(primary?'primary':'')+(magnet?' magnetic':'')+'" href="'+href+'"><span>'+text+' '+arrow+'</span></a>';
export const image=(id,alt='',cls='',eager=false)=>'<img class="'+cls+'" src="assets/images/'+id+'.'+(id.startsWith('fold-')&&!['fold-print','fold-card'].includes(id)?'webp':'svg')+'" alt="'+esc(alt)+'" width="1280" height="900" '+(eager?'fetchpriority="high"':'loading="lazy"')+'>';
export const header=route=>'<div class="wrap header-inner"><a class="brand" href="#/" aria-label="VOID — главная">void<span> / 01</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Меню <span>+</span></button><nav id="navigation" aria-label="Основная навигация">'+[['projects','Работы'],['services','Услуги'],['studio','Студия'],['contact','Контакты']].map(([r,t])=>'<a href="#/'+r+'" '+(route.startsWith(r)?'aria-current="page"':'')+'>'+t+'</a>').join('')+'<button class="motion-toggle" data-motion>Анимация: вкл.</button></nav>'+button('Обсудить проект','#/contact',true)+'</div>';
export const footer=()=>'<div class="wrap"><div class="footer-top"><p class="eyebrow">СЛЕДУЮЩИЙ ПРОЕКТ</p><h2>Есть задача?<br>Давайте найдём форму.</h2>'+button('Обсудить проект','#/contact',true,true)+'</div><div class="footer-bottom"><a class="brand" href="#/" aria-label="VOID — главная">void<span> / 01</span></a><nav aria-label="Навигация в подвале"><a href="#/projects">Работы</a><a href="#/services">Услуги</a><a href="#/studio">Студия</a><a href="#/contact">Контакты</a></nav><button class="motion-toggle" data-motion>Анимация: вкл.</button><small>© 2026 VOID · Portfolio concept<br>Концептуальные работы. Форма без отправки.</small></div></div>';
export const serviceRows=()=>services.map((s,i)=>'<details class="service-row" id="'+s.id+'"><summary><span class="eyebrow">0'+(i+1)+'</span><h3>'+s.title+'</h3><span class="plus">+</span></summary><div class="service-body"><p>'+s.text+'</p><p class="muted">'+s.items+'</p><div class="actions">'+button('Смотреть пример','#/projects/'+s.project)+button('Обсудить задачу','#/contact?service='+s.id)+'</div></div></details>').join('');
export const projectCard=(p,cls='')=>'<article class="project-card '+cls+'"><a href="#/projects/'+p.id+'"><div class="media">'+image(p.id==='fold'?'fold-cover':p.id+'-cover',p.name+' — '+p.desc)+'</div><div class="project-caption"><h3>'+p.name+'</h3><p>'+p.type.join(' / ')+'</p><span>2026 '+arrow+'</span></div></a></article>';
export function lumenSVG(){return '<svg viewBox="0 0 1000 580" role="img" aria-label="LUMEN — знак из трёх сегментов и словесное написание"><g class="grid" stroke="currentColor" opacity=".16" fill="none"><path d="M200 70H800M200 410H800M500 30V470M330 30V470M670 30V470"/><circle cx="500" cy="240" r="170"/><circle cx="500" cy="240" r="110"/></g><g class="segments" fill="none" stroke="currentColor" stroke-width="48" stroke-linecap="butt">'+[0,120,240].map((v,i)=>'<g class="segment s'+i+'" style="transform-origin:500px 240px"><path transform="rotate('+v+' 500 240)" d="M 543.26 106.85 A 140 140 0 0 1 604.04 333.68"/></g>').join('')+'</g><text class="lumen-word" x="500" y="515" text-anchor="middle" font-family="Inter,Arial,sans-serif" font-size="66" letter-spacing="17">LUMEN</text></svg>';}
