import {services,projects} from './data.js';
import {esc} from './components.js';
let draft={name:'',email:'',company:'',task:'',url:'',budget:'Обсудим',deadline:'Обсудим',services:[],case:''},success=false;
export const getDraft=()=>structuredClone(draft);
const field=(id,label,type='text',required=false,help='')=>'<div class="field '+(id==='task'?'full':'')+'"><label for="brief-'+id+'">'+label+(required?' *':'')+'</label>'+(type==='textarea'?'<textarea id="brief-'+id+'" name="'+id+'" maxlength="2000" aria-required="true" aria-describedby="help-'+id+' error-'+id+'">'+esc(draft[id])+'</textarea>':'<input type="'+type+'" id="brief-'+id+'" name="'+id+'" value="'+esc(draft[id])+'" '+(required?'aria-required="true" ':'')+'maxlength="'+(id==='url'?500:120)+'" aria-describedby="help-'+id+' error-'+id+'" '+(id==='email'?'autocomplete="email"':id==='name'?'autocomplete="name"':'')+'>')+'<small id="help-'+id+'">'+help+'</small><span class="error" id="error-'+id+'" data-error="'+id+'"></span></div>';
export function capture(){const f=document.querySelector('.brief');if(!f)return;for(const key of ['name','email','company','task','url','budget','deadline'])draft[key]=f.elements[key].value;draft.services=[...f.querySelectorAll('[name=services]:checked')].map(e=>e.value);}
export function initForm(params){const c=params.get('case'),s=params.get('service');if(projects.some(p=>p.id===c))draft.case=c;if(services.some(x=>x.id===s)&&!draft.services.includes(s))draft.services.push(s);success=false;render();}
function render(){const host=document.querySelector('#brief-host');if(!host)return;
 if(success){host.innerHTML='<section class="success" tabindex="-1"><span class="eyebrow">ГОТОВО К ОБСУЖДЕНИЮ</span><h2>Демо-заявка подготовлена.</h2><p>Данные никуда не отправлены.</p><dl><dt>Имя</dt><dd>'+esc(draft.name)+'</dd><dt>Email</dt><dd>'+esc(draft.email)+'</dd><dt>Задача</dt><dd>'+esc(draft.task)+'</dd><dt>Направления</dt><dd>'+draft.services.map(id=>esc(services.find(s=>s.id===id).title)).join(', ')+'</dd>'+(draft.case?'<dt>Референс</dt><dd>'+esc(draft.case.toUpperCase())+'</dd>':'')+'<dt>Бюджет / срок</dt><dd>'+esc(draft.budget)+' / '+esc(draft.deadline)+'</dd></dl><div class="actions"><button class="button" data-edit>Изменить</button><button class="button" data-clear>Очистить</button></div></section>';host.querySelector('[data-edit]').onclick=()=>{success=false;render();host.querySelector('input').focus();};host.querySelector('[data-clear]').onclick=()=>{draft={name:'',email:'',company:'',task:'',url:'',budget:'Обсудим',deadline:'Обсудим',services:[],case:''};success=false;render();host.querySelector('input').focus();};host.querySelector('.success').focus();return;}
 host.innerHTML='<form class="brief" novalidate>'+field('name','Как к вам обращаться','text',true)+field('email','Email','email',true)+field('company','Компания / проект')+field('url','Ссылка на материалы','url',false,'Необязательно. Ссылка https://…')+'<fieldset><legend>Что нужно *</legend><div class="service-options">'+services.map(s=>'<label class="check-label"><input type="checkbox" name="services" value="'+s.id+'" '+(draft.services.includes(s.id)?'checked':'')+'>'+s.title+'</label>').join('')+'</div><p class="error" data-error="services" id="error-services"></p></fieldset>'+field('task','Расскажите о задаче','textarea',true,'До 2 000 символов. Продукт, аудитория, желаемый результат.')+['budget','deadline'].map((id,i)=>'<div class="field"><label for="brief-'+id+'">'+(i?'Срок':'Бюджет')+'</label><select id="brief-'+id+'" name="'+id+'">'+(i?['Обсудим','Есть ориентир','Пока неизвестно']:['Обсудим','Бюджет определён','Пока неизвестно']).map(v=>'<option '+(draft[id]===v?'selected':'')+'>'+v+'</option>').join('')+'</select></div>').join('')+(draft.case?'<div class="context full"><span>Контекст: '+esc(draft.case.toUpperCase())+'</span><button type="button" data-remove-case aria-label="Убрать контекст кейса">×</button></div>':'')+'<p class="brief-note full">* Обязательные поля. Данные остаются в памяти этой вкладки до обновления. Форма не отправляет письма и не сохраняет контакты в браузере.</p><div class="full"><button class="button primary" type="submit">Подготовить демо-заявку ↗</button></div><p class="error full" id="form-status" role="alert"></p></form>';
 host.querySelector('[data-remove-case]')?.addEventListener('click',()=>{capture();draft.case='';history.replaceState(null,'','#/contact');render();host.querySelector('input').focus();});
 host.querySelector('form').addEventListener('submit',e=>{e.preventDefault();capture();const errors={};if(!draft.name.trim())errors.name='Укажите, как к вам обращаться.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email.trim()))errors.email='Проверьте email, например name@example.com.';if(!draft.services.length)errors.services='Выберите хотя бы одно направление.';if(draft.task.trim().length<10)errors.task='Добавьте хотя бы 10 символов о задаче.';if(draft.url.trim()){try{const u=new URL(draft.url);if(!['http:','https:'].includes(u.protocol))throw Error();}catch{errors.url='Укажите полную ссылку http:// или https://.';}}
  host.querySelectorAll('[data-error]').forEach(el=>el.textContent=errors[el.dataset.error]||'');for(const id of ['name','email','task','url'])host.querySelector('[name='+id+']').setAttribute('aria-invalid',!!errors[id]);if(Object.keys(errors).length){host.querySelector('#form-status').textContent='Проверьте отмеченные поля. Введённые данные сохранены.';(host.querySelector('[name='+Object.keys(errors)[0]+']')).focus();return;}success=true;render();
 });
}
