import * as T from '../assets/vendor/three/three.module.js';
import {mergeGeometries} from '../assets/vendor/three/BufferGeometryUtils.js';
import {buildComposition} from './model.js';
import {move,floorAt,allowed} from './physics.js';
import {SSAOPass} from './vendor/SSAOPass.js';
import {OutputPass} from './vendor/OutputPass.js';
const $=s=>document.querySelector(s),host=$('#stage'),status=$('#status');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.87;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;renderer.transmissionResolutionScale=.5;host.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#d8d7d2');const camera=new T.PerspectiveCamera(44,5/3,.06,120);
const model=await buildComposition({scene,renderer});
// Movable entrance and sliding leaf are excluded from static geometry batching.
const entry=model.parts.entry,hinge=new T.Group();hinge.position.set(-.7205,0,-.025);entry.add(hinge);entry.updateMatrixWorld(true);
for(const o of [...entry.children])if(['Timber entry leaf','Door pull fixing','Brushed door pull'].includes(o.name))hinge.attach(o);
const slider=new T.Group();model.building.add(slider);model.building.updateMatrixWorld(true);
for(const o of [...model.parts.south.children])if(o.position.x>.227&&o.position.x<1.427&&o.name!=='Mullion')slider.attach(o);
for(const o of [...model.building.children])if(['Slider interlock','Pull mount','Recessed pull'].includes(o.name))slider.attach(o);
hinge.userData.moving=true;slider.userData.moving=true;
// Merge by material; timber variation becomes vertex colour, retaining the mapped grain.
const buckets=new Map(),timber=new Map();model.building.updateMatrixWorld(true);
model.building.traverse(o=>{if(!o.isMesh)return;for(let p=o;p;p=p.parent)if(p.userData.moving)return;
 let mat=o.material,key=mat.uuid,g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();g.applyMatrix4(o.matrixWorld);
 if(mat.map){key='wood-'+mat.map.uuid;let shared=timber.get(key);if(!shared){shared=mat.clone();shared.color.set(0xffffff);shared.vertexColors=true;timber.set(key,shared)}const c=new Float32Array(g.attributes.position.count*3);for(let i=0;i<c.length;i+=3){c[i]=mat.color.r;c[i+1]=mat.color.g;c[i+2]=mat.color.b}g.setAttribute('color',new T.BufferAttribute(c,3));mat=shared;}
 if(!buckets.has(key))buckets.set(key,{mat,geos:[],objects:[]});buckets.get(key).geos.push(g);buckets.get(key).objects.push(o);
});
for(const b of buckets.values()){const g=mergeGeometries(b.geos);if(!g)throw Error('Не удалось собрать геометрию');const mesh=new T.Mesh(g,b.mat);mesh.castShadow=b.mat!==model.glass;mesh.receiveShadow=true;model.building.add(mesh);b.objects.forEach(o=>o.removeFromParent());b.geos.forEach(g=>g.dispose());}
const ground=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:'#c4c2b9',roughness:.96}));ground.rotation.x=-Math.PI/2;ground.position.set(4.8,-.335,3.3);ground.receiveShadow=true;scene.add(ground);
const sun=new T.DirectionalLight('#fff5e8',3.2);sun.position.set(-8,11,12);sun.target.position.set(4.8,.8,3.3);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:1,far:40});sun.shadow.bias=-.00008;sun.shadow.normalBias=.01;scene.add(sun,sun.target);
const envData=new Float32Array(256*128*4),top=new T.Color('#dce4ed'),bottom=new T.Color('#a09a90'),color=new T.Color();for(let y=0;y<128;y++){color.lerpColors(bottom,top,((1-Math.cos(Math.PI*(y+.5)/128))/2)**.8);for(let x=0;x<256;x++){const i=(y*256+x)*4;envData.set([color.r,color.g,color.b,1],i)}}const env=new T.DataTexture(envData,256,128,T.RGBAFormat,T.FloatType);env.mapping=T.EquirectangularReflectionMapping;env.needsUpdate=true;scene.environment=env;scene.environmentIntensity=.75;
const target=new T.WebGLRenderTarget(1,1,{type:T.HalfFloatType,samples:4}),ao=new SSAOPass(scene,camera,1,1,16),output=new OutputPass();output.renderToScreen=true;ao.kernelRadius=.13;ao.minDistance=.00012;ao.maxDistance=.005;
let seed=804;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};ao.kernel.forEach((v,i)=>v.set(random()*2-1,random()*2-1,random()).normalize().multiplyScalar(.1+.9*(i/16)**2));
const focus=new T.Vector3(4.3,1.25,3.85),spherical=new T.Spherical(),keys=new Set(),canvas=renderer.domElement;
let released=false,disposed=false,queued=0,walking=false,drag=null,yaw=0,pitch=0,last=0,frames=0,drawMs=0,doorOpen=false,fast=true;const frameTimes=[];
canvas.tabIndex=0;canvas.setAttribute('aria-label','Модель павильона. Перетаскивание — обзор. В прогулке WASD или стрелки — движение. Esc — выход.');
function doors(open){doorOpen=open;hinge.rotation.y=open?-Math.PI/2:0;slider.position.x=open?1.227:0;slider.position.z=open?.075:0;renderer.shadowMap.needsUpdate=true;}
function draw(){if(disposed||document.hidden)return;const start=performance.now(),w=host.clientWidth,h=host.clientHeight,dpr=walking&&fast?Math.min(1,1024/w):Math.min(devicePixelRatio,1);renderer.setPixelRatio(dpr);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){renderer.setSize(w,h,false);target.setSize(canvas.width,canvas.height);ao.setSize(Math.ceil(canvas.width/2),Math.ceil(canvas.height/2));camera.aspect=w/h;camera.updateProjectionMatrix()}
renderer.info.autoReset=false;renderer.info.reset();renderer.setRenderTarget(target);renderer.clear();renderer.render(scene,camera);const hidden=[];model.building.traverse(o=>{if(o.isMesh&&o.visible&&o.material===model.glass){o.visible=false;hidden.push(o)}});if(!(walking&&fast))ao.render(renderer,null,target);hidden.forEach(o=>o.visible=true);output.render(renderer,null,target);frames++;drawMs=performance.now()-start;
}
function requestDraw(){if(!queued&&!disposed&&!document.hidden)queued=requestAnimationFrame(t=>{queued=0;tick(t)})}
function look(){camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0)}
function tick(t){const dt=Math.min(.05,last?(t-last)/1000:0);if(last&&walking&&keys.size){frameTimes.push(t-last);if(frameTimes.length>1200)frameTimes.shift()}last=t;if(walking&&keys.size){let a=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),b=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0);const scale=1.7*dt/Math.max(1,Math.hypot(a,b)),p=move(camera.position,(Math.cos(yaw)*a-Math.sin(yaw)*b)*scale,(-Math.sin(yaw)*a-Math.cos(yaw)*b)*scale);camera.position.set(p.x,p.y,p.z)}draw();if(walking&&keys.size)requestDraw();}
function stopWalk(){walking=false;keys.clear();last=0;document.exitPointerLock?.();host.classList.remove('walking');$('#exit').hidden=true;$('#walk').hidden=false;$('#hint').textContent='Потяните мышью или пальцем для обзора. Внешний вид возвращает общую камеру. Готовые внутренние ракурсы доступны без прогулки.';}
function reset(){stopWalk();doors(false);camera.fov=44;camera.position.set(-3.7,3.15,15.4);camera.lookAt(focus);spherical.setFromVector3(camera.position.clone().sub(focus));camera.updateProjectionMatrix();status.textContent='Живая 3D · внешний вид · свет и отражения отличаются от презентационного рендера';requestDraw();}
const views={hall:{p:[1.1,1.615,1.6],t:[3.8,1.4,1.9]},living:{p:[3.2,1.615,5.1],t:[6.4,1.15,1]},terrace:{p:[5.3,1.575,8.4],t:[5.4,1.3,2.5]}};
let interiorView=false;
function preset(name){stopWalk();interiorView=true;doors(true);const v=views[name];camera.position.fromArray(v.p);camera.fov=65;camera.rotation.order='YXZ';camera.lookAt(new T.Vector3(...v.t));yaw=camera.rotation.y;pitch=camera.rotation.x;camera.updateProjectionMatrix();status.textContent='Живая 3D · '+({hall:'прихожая',living:'кухня-гостиная',terrace:'терраса'}[name]);requestDraw();}
function startWalk(){stopWalk();walking=true;interiorView=true;doors(true);camera.fov=65;camera.updateProjectionMatrix();camera.position.set(-1.75,floorAt(-1.75,1.48)+1.6,1.48);yaw=-Math.PI/2;pitch=0;look();host.classList.add('walking');$('#walk').hidden=true;$('#exit').hidden=false;$('#hint').textContent='WASD / стрелки — идти; мышь — обзор (нажмите на сцену), либо тяните с зажатой кнопкой. Вход → через проём справа в гостиную → стеклянная дверь → терраса. Esc — выход.';status.textContent='Прогулка · облегчённый рендер: ниже разрешение и без экранных контактных теней. Стены, мебель и край террасы ограничивают движение';canvas.focus();requestDraw();}
function orbit(dx,dy){if(walking||interiorView){yaw-=dx;pitch=T.MathUtils.clamp(pitch-dy,-1.2,1.2);look()}else{spherical.theta-=dx;spherical.phi=T.MathUtils.clamp(spherical.phi+dy,.35,1.52);camera.position.copy(focus).add(new T.Vector3().setFromSpherical(spherical));camera.lookAt(focus)}requestDraw()}
function zoom(scale){if(walking||interiorView){camera.fov=T.MathUtils.clamp(camera.fov*scale,40,80);camera.updateProjectionMatrix()}else{spherical.radius=T.MathUtils.clamp(spherical.radius*scale,8,28);orbit(0,0)}requestDraw()}
canvas.addEventListener('pointerdown',e=>{canvas.focus();drag={x:e.clientX,y:e.clientY};try{canvas.setPointerCapture(e.pointerId)}catch{}if(walking&&e.pointerType==='mouse'){const result=canvas.requestPointerLock?.();result?.catch(()=>{});}});
canvas.addEventListener('pointermove',e=>{if(document.pointerLockElement===canvas){orbit(e.movementX*.002,e.movementY*.002);return}if(!drag)return;orbit((e.clientX-drag.x)*.004,(e.clientY-drag.y)*.003);drag={x:e.clientX,y:e.clientY}});
for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>drag=null);
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(e.deltaY*.001))},{passive:false});
addEventListener('keydown',e=>{if(e.code==='Escape'){if(walking){stopWalk();interiorView=false;reset()}else parent.postMessage('axis:close',location.origin);return}if(walking&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();keys.add(e.code);requestDraw()}});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();last=0});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&walking){stopWalk();interiorView=false;reset()}});
document.addEventListener('visibilitychange',()=>{keys.clear();last=0;if(!document.hidden)requestDraw()});addEventListener('resize',requestDraw);
$('#reset').onclick=()=>{interiorView=false;reset()};$('#closer').onclick=()=>zoom(.9);$('#farther').onclick=()=>zoom(1.1);$('#walk').onclick=startWalk;$('#exit').onclick=()=>{interiorView=false;reset()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>preset(b.dataset.view));
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(disposed)return;disposed=true;keys.clear();$('#loading').hidden=false;$('#loading').style.display='grid';$('#loading span').textContent='Связь с графическим устройством потеряна. Вернитесь к изображению и откройте 3D снова.'});
function dispose(){if(released)return;released=true;disposed=true;cancelAnimationFrame(queued);keys.clear();document.exitPointerLock?.();const geos=new Set(model.geo),mats=new Set(model.mats),textures=new Set(model.tex);scene.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)mats.add(o.material)});geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());env.dispose();target.dispose();ao.dispose();ao.ssaoMaterial.dispose();ao.noiseTexture.dispose();output.dispose();sun.shadow.dispose();renderer.dispose();renderer.forceContextLoss()}
addEventListener('pagehide',dispose,{once:true});addEventListener('pageshow',e=>{if(e.persisted)location.reload()});
window.horizon={scene,camera,renderer,model,views,reset,preset,startWalk,allowed,move,dispose,capture(){draw();return canvas.toDataURL('image/webp',.93).split(',')[1]},get info(){return{ready:!$('#loading').hidden===false,frames,drawMs,walking,fast,doorOpen,camera:camera.position.toArray(),calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,frameTimes:[...frameTimes],buffer:[canvas.width,canvas.height]}}};
camera.position.set(-3.7,3.15,15.4);camera.lookAt(focus);await renderer.compileAsync(scene,camera);reset();draw();$('#loading').hidden=true;$('#loading').style.display='none';document.querySelectorAll('button').forEach(b=>b.disabled=false);window.horizonReady=true;
