import {mountPavilion} from './pavilion.js';
import{projects,projectById}from'./data.js';import{header,footer,esc}from'./components.js';import{home,listing,projectPage,servicePage,studioPage,processPage,contactPage,notFound}from'./pages.js';import{mountForm}from'./form.js';import{mountModel}from'./model.js';
const app=document.querySelector('#app'),mq=matchMedia('(prefers-reduced-motion: reduce)');let stopped=false;try{stopped=localStorage.getItem('axis-motion-v1')==='off';}catch{}let cleanup=()=>{},current='',scrolls=new Map(),navigating=false;history.scrollRestoration='manual';
export const motionOff=()=>stopped||mq.matches;
function setMotion(){document.documentElement.classList.toggle('no-motion',motionOff());document.querySelectorAll('.motion-toggle').forEach(b=>{b.setAttribute('aria-pressed',String(motionOff()));b.textContent=mq.matches?'Движение выключено системой':stopped?'Включить движение':'Без движения';});dispatchEvent(new CustomEvent('axis:motion',{detail:motionOff()}));}
mq.addEventListener('change',setMotion);
function route(){const raw=location.hash.startsWith('#/')?location.hash.slice(2):'',parts=raw.split('?');return{path:parts[0].replace(/\/$/,''),query:new URLSearchParams(parts[1]),key:location.hash||'#/'};}
function render(){const{path,query,key}=route();if(current)scrolls.set(current,scrollY);cleanup();document.body.classList.remove('locked');const p=path.startsWith('projects/')?projectById(path.split('/')[1]):null;const content=path===''?home():path==='projects'?listing(query):p?projectPage(p):path==='services'?servicePage():path==='studio'?studioPage():path==='process'?processPage():path==='contacts'?contactPage():notFound();app.innerHTML=header(path)+'<main id="main">'+content+'</main>'+footer();document.title=(p?p.title:({'':'Архитектура. От контекста к пространству.','projects':'Проекты','services':'Услуги','studio':'Бюро','process':'Подход','contacts':'Контакты'}[path]||'Страница не найдена'))+' — AXIS';const tasks=[],abort=new AbortController(),opts={signal:abort.signal};tasks.push(()=>abort.abort());current=key;
 const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#site-nav');const closeMenu=()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('open');};menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);},opts);addEventListener('resize',()=>{if(innerWidth>1000)closeMenu();},opts);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();}},opts);
 document.querySelector('.motion-toggle').addEventListener('click',()=>{if(mq.matches)return;stopped=!stopped;try{localStorage.setItem('axis-motion-v1',stopped?'off':'on');}catch{}setMotion();},opts);setMotion();
 document.querySelectorAll('[data-anchor]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();document.getElementById(a.dataset.anchor)?.scrollIntoView({behavior:motionOff()?'instant':'smooth'});},opts));
 if(path==='contacts')tasks.push(mountForm(document.querySelector('#contact-root'),query));
 tasks.push(mountPavilion());
 if(p?.scene&&p.id!=='courtyard')tasks.push(mountModel(document.querySelector('[data-model]'),motionOff));
 if(p){let active=0,trigger=null;const dialog=document.createElement('dialog');dialog.className='lightbox';dialog.setAttribute('aria-label','Галерея проекта '+p.title);dialog.innerHTML='<div class="lightbox-head"><span>'+p.code+' / '+p.title+'</span><button data-close aria-label="Закрыть галерею">Закрыть ×</button></div><img alt=""><div class="lightbox-foot"><button data-prev aria-label="Предыдущее изображение">←</button><span data-caption></span><button data-next aria-label="Следующее изображение">→</button></div>';app.append(dialog);const update=()=>{dialog.querySelector('img').src='./assets/images/'+p.gallery[active]+'.webp';dialog.querySelector('img').alt=p.captions[active];dialog.querySelector('[data-caption]').textContent=(active+1)+' / '+p.gallery.length+' · '+p.captions[active];};document.querySelectorAll('[data-gallery]').forEach(b=>b.addEventListener('click',()=>{trigger=b;active=+b.dataset.gallery;update();dialog.showModal();document.body.classList.add('locked');},opts));dialog.querySelector('[data-close]').addEventListener('click',()=>dialog.close(),opts);dialog.querySelector('[data-prev]').addEventListener('click',()=>{active=(active-1+p.gallery.length)%p.gallery.length;update();},opts);dialog.querySelector('[data-next]').addEventListener('click',()=>{active=(active+1)%p.gallery.length;update();},opts);dialog.addEventListener('close',()=>{document.body.classList.remove('locked');trigger?.focus();},opts);dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close();}},opts);dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight')dialog.querySelector('[data-next]').click();if(e.key==='ArrowLeft')dialog.querySelector('[data-prev]').click();},opts);}
 const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){if(!motionOff())e.target.classList.add('revealing');io.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.studio-preview,.triptych').forEach(el=>{el.classList.add('reveal');io.observe(el);});tasks.push(()=>io.disconnect());cleanup=()=>tasks.reverse().forEach(fn=>fn());
 requestAnimationFrame(()=>{const restore=navigating?0:scrolls.get(key)||0;scrollTo({top:restore,behavior:'instant'});if(navigating)document.querySelector('h1')?.focus({preventScroll:true});navigating=false;if(path==='services'&&query.get('focus'))document.getElementById('service-'+query.get('focus'))?.scrollIntoView({behavior:'instant'});});
}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#/"]');if(a&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey){navigating=true;if(a.hash===location.hash){e.preventDefault();scrollTo({top:0,behavior:motionOff()?'instant':'smooth'});}}});addEventListener('hashchange',render);addEventListener('pagehide',()=>cleanup());render();window.axisReady=true;

