import{projects,services,asset}from'./data.js';
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const href=(route,query={})=>'#/'+route+(Object.keys(query).length?'?'+new URLSearchParams(query):'');
export function img(name,alt,cls='',priority=false){return '<img class="'+cls+'" src="./assets/images/'+name+'.webp" '+(name.startsWith('interior-')?'srcset="./assets/images/'+name+'-640.webp 640w, ./assets/images/'+name+'.webp 1536w" sizes="(max-width:700px) calc(100vw - 48px), 70vw"':'')+' alt="'+esc(alt)+'" width="1600" height="1067" '+(priority?'fetchpriority="high"':'loading="lazy"')+' decoding="async">';}
export const arrow='<span aria-hidden="true">↗</span>';
export function card(p,{wide=false,priority=false}={}){return '<a class="project-card '+(wide?'wide':'')+'" href="'+href('projects/'+p.id)+'"><div class="project-image">'+img(asset(p)+'-cover',p.title,'',priority)+'<span class="image-link">'+arrow+'</span></div><div class="project-meta"><span class="eyebrow">'+p.code+'</span><h3>'+p.title+'</h3><span>'+p.kind+'</span></div><div class="project-facts"><span>Концептуальный проект</span><span>'+({courtyard:'9,6 × 6,6 м · кухня-гостиная · терраса',atrium:'Три уровня · центральный атриум',interior:'Жилое пространство · дуб и тёплый свет','linear-park':'Пешеходный маршрут · озеленение'}[p.id]||p.category)+'</span><span>Подробнее ↗</span></div></a>';}
export function header(route){return '<header class="header"><div class="wrap header-inner"><a href="#/" class="logo" aria-label="AXIS — главная">AXIS</a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav">Меню <span aria-hidden="true">+</span></button><nav id="site-nav" aria-label="Основная навигация">'+[['projects','Проекты'],['services','Услуги'],['studio','Бюро'],['process','Подход'],['contacts','Контакты']].map(([url,label])=>'<a href="'+href(url)+'" '+(route===url||route.startsWith(url+'/')?'aria-current="page"':'')+'>'+label+'</a>').join('')+'</nav><a class="header-cta text-link" href="#/contacts">Обсудить проект '+arrow+'</a></div></header>';}
export function footer(){return '<footer class="footer"><div class="wrap"><div class="footer-top"><span class="eyebrow">НАЧАЛО ДИАЛОГА</span><a class="footer-invite" href="#/contacts">Обсудим пространство,<br>которое вы хотите создать '+arrow+'</a></div><div class="footer-bottom"><a class="logo" href="#/" aria-label="AXIS — главная">AXIS</a><p>Архитектура.<br>От контекста к пространству.</p><nav aria-label="Навигация в подвале"><a href="#/projects">Проекты</a><a href="#/services">Услуги</a><a href="#/contacts">Контакты</a></nav><button class="motion-toggle" aria-pressed="false">Без движения</button></div><div class="legal"><span>© AXIS · Portfolio concept</span><span>Концептуальные проекты. Реальные заявки не отправляются.</span></div></div></footer>';}
export function intro(label,title,text=''){return '<section class="page-intro wrap"><p class="eyebrow">'+label+'</p><h1 tabindex="-1">'+title+'</h1>'+(text?'<p class="lead">'+text+'</p>':'')+'</section>';}
export function sectionHeading(num,title,link=''){return '<div class="section-heading"><span class="eyebrow">'+num+'</span><h2>'+title+'</h2>'+link+'</div>';}
export function contextLink(project,service,source,label='Обсудить похожий проект'){return '<a class="button" href="'+href('contacts',{...(project?{project}:{}),...(service?{service}:{}),source})+'">'+label+' '+arrow+'</a>';}
export function triptych(){return '<div class="triptych"><figure><img src="./assets/diagrams/horizon-plan.svg" width="900" height="600" loading="lazy" alt="План павильона Горизонт"><figcaption>01 / План</figcaption></figure><figure>'+img('horizon-model','Горизонт — кадр WebGL')+'<figcaption>02 / Интерактивная модель</figcaption></figure><figure>'+img('horizon-cover','Горизонт — презентационный рендер')+'<figcaption>03 / Презентационный рендер</figcaption></figure></div>';}
