import{projects,services,projectById,serviceById}from'./data.js';import{esc}from'./components.js';
let draft={},success=false,context={};
export function mountForm(root,query){if(query.get('project')||query.get('service')){context={project:projectById(query.get('project'))?.id||'',service:serviceById(query.get('service'))?.id||'',source:(query.get('source')||'').slice(0,120)};success=false;}const controller=new AbortController(),opts={signal:controller.signal};
 const field=(name,label,type='text',required=false,wide=false)=>'<label class="field '+(wide?'full':'')+'" for="'+name+'">'+label+(required?' *':'')+'<input id="'+name+'" name="'+name+'" type="'+type+'" '+(required?'required':'')+' maxlength="'+(name==='email'?180:100)+'" autocomplete="'+({name:'name',email:'email',phone:'tel'}[name]||'off')+'" value="'+esc(draft[name])+'" aria-describedby="'+name+'-error"><span class="error" id="'+name+'-error"></span></label>';
 const options=(name,label,items,required=false)=>'<label class="field" for="'+name+'">'+label+(required?' *':'')+'<select name="'+name+'" id="'+name+'" '+(required?'required':'')+' aria-describedby="'+name+'-error"><option value="">'+(required?'Выберите тип':'Нужна консультация')+'</option>'+items.map(([v,t])=>'<option value="'+esc(v)+'" '+((draft[name]||context[name])===v?'selected':'')+'>'+esc(t)+'</option>').join('')+'</select><span class="error" id="'+name+'-error"></span></label>';
 function render(){if(success){root.innerHTML='<section class="form-success" tabindex="-1"><p class="eyebrow">ДЕМОНСТРАЦИОННАЯ ФОРМА</p><h2>Данные проверены.</h2><p>Это демонстрационная форма; заявка не отправлена. Контакты остаются только в памяти этой страницы.</p><dl class="form-summary">'+[['Имя',draft.name],['Email',draft.email],['Тип объекта',draft.type],['Направление',serviceById(draft.service)?.name||'Консультация'],...(context.project?[['Пример',projectById(context.project).title]]:[])].map(([a,b])=>'<dt>'+a+'</dt><dd>'+esc(b)+'</dd>').join('')+'</dl><div class="actions"><button class="button" data-edit>Изменить данные</button><button class="link-button" data-clear>Очистить форму</button></div></section>';return;}
 root.innerHTML='<form class="contact-form" novalidate>'+(context.project?'<div class="form-context"><div><small>ПРОЕКТ ДЛЯ ОБСУЖДЕНИЯ</small><p>'+esc(projectById(context.project).title)+'</p></div><button type="button" class="link-button" data-clear-context>Убрать пример</button></div>':'')+'<div class="form-grid">'+field('name','Имя','text',true)+field('email','Email','email',true)+field('phone','Телефон, необязательно','tel')+options('type','Тип объекта',[['Частный дом','Частный дом'],['Общественное здание','Общественное здание'],['Интерьер','Интерьер'],['Территория','Территория'],['Пока не определено','Пока не определено']],true)+options('service','Направление',services.map(s=>[s.id,s.name]))+'<label class="field full" for="task">Расскажите о задаче *<textarea id="task" name="task" required minlength="10" maxlength="3000" aria-describedby="task-error" placeholder="Что вы хотите создать или изменить?">'+esc(draft.task)+'</textarea><span class="error" id="task-error"></span></label></div><details '+(draft.region||draft.area||draft.timing?'open':'')+'><summary>Дополнительные сведения · необязательно</summary><div class="form-grid">'+field('region','Место / регион')+field('area','Ориентировочная площадь')+field('timing','Желаемые сроки','text',false,true)+'</div></details><p class="model-note">* Обязательные поля. Не указывайте чувствительные данные. Файлы и реальные отправки не подключены.</p><div class="form-submit"><button class="button" type="submit">Проверить демозаявку <span aria-hidden="true">↗</span></button><p>Проверка выполняется в браузере. Данные не отправляются на сервер.</p></div></form>';}
 root.addEventListener('input',e=>{if(e.target.name){draft[e.target.name]=e.target.value;clearError(e.target);}},opts);root.addEventListener('change',e=>{if(e.target.name){draft[e.target.name]=e.target.value;clearError(e.target);}},opts);
 function clearError(input){input.removeAttribute('aria-invalid');const error=root.querySelector('#'+input.name+'-error');if(error)error.textContent='';}
 root.addEventListener('submit',e=>{e.preventDefault();const form=e.target;draft=Object.fromEntries(new FormData(form));const errors={};if(!draft.name.trim())errors.name='Укажите имя.';if(!draft.email.trim()||!form.elements.email.validity.valid)errors.email='Укажите email в формате name@example.com.';if(draft.phone&&draft.phone.replace(/\D/g,'').length<7)errors.phone='Проверьте номер или оставьте поле пустым.';if(!draft.type)errors.type='Выберите тип объекта или «Пока не определено».';if(draft.task.trim().length<10)errors.task='Опишите задачу хотя бы в нескольких словах (от 10 символов).';for(const[name,message]of Object.entries(errors)){form.elements[name].setAttribute('aria-invalid','true');root.querySelector('#'+name+'-error').textContent=message;}if(Object.keys(errors).length){form.elements[Object.keys(errors)[0]].focus();return;}success=true;render();root.querySelector('.form-success').focus();},opts);
 root.addEventListener('click',e=>{if(e.target.closest('[data-edit]')){success=false;render();root.querySelector('input').focus();}if(e.target.closest('[data-clear]')){draft={};context={};success=false;history.replaceState(history.state,'','#/contacts');render();root.querySelector('input').focus();}if(e.target.closest('[data-clear-context]')){context.project='';const url=new URL(location.href),[path,search]=url.hash.split('?'),q=new URLSearchParams(search);q.delete('project');history.replaceState(history.state,'',path+(q.size?'?'+q:''));render();}},opts);
 render();return()=>controller.abort();}

