export const pavilionButton=()=>'<div class="pavilion-launch"><button class="button" data-pavilion>Открыть 3D и прогулку ↗</button><p>«Горизонт» · концептуальный павильон. На странице — презентационный рендер; интерактивный свет проще.</p></div>';
export const pavilionSection=()=>'<section class="section wrap" id="model"><div class="section-heading"><span class="eyebrow">02 / ПРОСТРАНСТВО</span><h2>Внутри «Горизонта»</h2></div><img class="case-cover" src="./assets/images/horizon-cover.webp" width="1600" height="960" loading="lazy" alt="Павильон Горизонт — презентационный рендер">'+pavilionButton()+'<p class="model-note">Вход → прихожая → кухня-гостиная → терраса. Доступны готовые ракурсы. Интерактивная сцена использует ту же архитектуру, но освещение и отражения отличаются от презентационного рендера. Концепция не является строительной документацией.</p></section>';
export function mountPavilion(){
 const buttons=[...document.querySelectorAll('[data-pavilion]')];if(!buttons.length)return()=>{};
 const abort=new AbortController();let dialog=null,trigger=null;
 const close=()=>{if(!dialog)return;const frame=dialog.querySelector('iframe');frame?.contentWindow?.horizon?.dispose();frame?.remove();dialog.close();dialog.remove();dialog=null;document.body.classList.remove('locked');trigger?.focus()};
 for(const button of buttons)button.addEventListener('click',()=>{if(dialog)return;trigger=button;dialog=document.createElement('dialog');dialog.className='pavilion-dialog';dialog.setAttribute('aria-label','Горизонт — интерактивный просмотр');dialog.innerHTML='<header><span>AXIS / ГОРИЗОНТ</span><button class="button" data-static>Вернуться к изображению ×</button></header><iframe title="Интерактивная модель и прогулка по павильону Горизонт" src="./pavilion/index.html"></iframe>';document.body.append(dialog);dialog.showModal();document.body.classList.add('locked');dialog.querySelector('[data-static]').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close()});},{signal:abort.signal});
 addEventListener('message',e=>{if(e.origin===location.origin&&e.source===dialog?.querySelector('iframe')?.contentWindow&&e.data==='axis:close')close()},{signal:abort.signal});
 return()=>{abort.abort();close()};
}
