import * as T from '../../assets/vendor/three/three.module.js';
const yieldUI=()=>globalThis.scheduler?.yield?globalThis.scheduler.yield():new Promise(r=>setTimeout(r,0));
const ease=(v)=>{v=Math.max(0,Math.min(1,v));return v*v*(3-2*v);};
let environmentData;
async function loadEnvironment(){if(!environmentData)environmentData=(async()=>{const base=new URL('../../assets/images/kinetic/',import.meta.url);const [meta,file]=await Promise.all([fetch(new URL('environment.json',base)).then(r=>{if(!r.ok)throw Error('Environment metadata');return r.json();}),fetch(new URL('environment.bin.gz',base)).then(r=>{if(!r.ok)throw Error('Environment texture');return r;})]);const data=await new Response(file.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();return {...meta,data:new Uint16Array(data)};})();try{return await environmentData;}catch(e){environmentData=null;throw e;}}
export async function createScene(host,{signal}={}){
 const baked=await loadEnvironment();if(!host.isConnected||signal?.aborted)throw Error('Stage removed');
 const canvas=document.createElement('canvas');canvas.style.visibility='hidden';canvas.setAttribute('aria-label','Объёмная сборка знака LUMEN');
 const renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'low-power'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
 const geometries=new Set(),materials=new Set(),textures=new Set();let dead=false,frames=0;
 const scene=new T.Scene();scene.background=new T.Color(0x33172c);scene.fog=new T.Fog(0x33172c,18,38);
 const camera=new T.PerspectiveCamera(34,1,.1,80);camera.position.set(0,5,15);camera.lookAt(0,2.1,0);
 scene.add(new T.HemisphereLight(0xffeddf,0x593347,1.15));const sun=new T.DirectionalLight(0xfff1da,2.6);sun.position.set(-5,10,6);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-7,right:7,top:7,bottom:-7,near:.5,far:30});sun.shadow.normalBias=.025;sun.shadow.bias=-.0001;scene.add(sun);const fill=new T.DirectionalLight(0xe1d0ff,.9);fill.position.set(6,5,-4);scene.add(fill);
 function mat(color,roughness=.5,metalness=0){const m=new T.MeshStandardMaterial({color,roughness,metalness,envMapIntensity:.7});materials.add(m);return m;}
 function mesh(g,m,parent=scene){geometries.add(g);const o=new T.Mesh(g,m);o.castShadow=o.receiveShadow=true;parent.add(o);return o;}
 const ground=mesh(new T.PlaneGeometry(100,100),mat(0x33172c,.95));ground.rotation.x=-Math.PI/2;ground.position.y=-.06;ground.castShadow=false;
 // Studio lighting is baked offline; no PMREM generation during user interaction.
 const environment=new T.DataTexture(baked.data,baked.width,baked.height,T.RGBAFormat,T.HalfFloatType);environment.mapping=T.CubeUVReflectionMapping;environment.minFilter=environment.magFilter=T.LinearFilter;environment.generateMipmaps=false;environment.colorSpace=T.LinearSRGBColorSpace;environment.needsUpdate=true;scene.environment=environment;
 const ring=new T.Group();scene.add(ring);const arc=new T.Shape(),angle=Math.PI/2-.11;arc.absarc(0,0,1.7,0,angle,false);arc.lineTo(Math.cos(angle)*1.02,Math.sin(angle)*1.02);arc.absarc(0,0,1.02,angle,0,true);arc.closePath();const shape=new T.ExtrudeGeometry(arc,{depth:.3,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.06,bevelThickness:.06,curveSegments:24});shape.translate(0,0,-.15);const pieces=[0xff765f,0xffa77b,0xf88d76,0xe45853].map(c=>mesh(shape,mat(c,.34,.04),ring));
 function print(bg){const c=document.createElement('canvas');c.width=512;c.height=640;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,512,640);x.fillStyle='#33172c';x.font='12px Arial';x.fillText('OBJECTS OF LIGHT / 01',35,48);x.font='bold 78px Arial';x.fillText('LUMEN',30,150);x.strokeStyle='#33172c';x.lineWidth=34;for(let i=0;i<4;i++){x.beginPath();x.arc(256,375,100,i*Math.PI/2+.1,(i+1)*Math.PI/2-.1);x.stroke();}x.font='16px Arial';x.fillText('A quiet presence.',35,580);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.anisotropy=4;textures.add(t);return t;}
 const paper=mat(0xffe4c8,.86);paper.map=print('#ffe4c8');const edge=mat(0xe5bba8);const card=mesh(new T.BoxGeometry(2.8,3.5,.055),[edge,edge,edge,edge,paper,edge]);card.rotation.set(-.15,-.17,.07);
 const coral=mat(0xff765f,.7);coral.map=print('#ff765f');const edge2=mat(0xc34543);const book=mesh(new T.BoxGeometry(2,2.7,.18),[edge2,edge2,edge2,edge2,coral,edge2]);book.position.set(3.9,1.5,1);book.rotation.set(-.12,-.28,-.12);
 function render(t){if(dead)return;const a=ease((t-.12)/.30),b=ease((t-.65)/.22);pieces.forEach((m,i)=>{const angle=i*Math.PI/2+.055,dist=(1-a)*1.4;m.position.set(Math.cos(angle+.7)*dist,Math.sin(angle+.7)*dist,(1-a)*[.25,-.6,.4,-.25][i]);m.rotation.set((1-a)*[.5,-.4,.2,-.3][i],(1-a)*.25,angle);});ring.position.set(-2.7*b,2.35-.5*b,0);ring.scale.setScalar(1-.14*b);ring.rotation.y=-.14+b*.25;card.visible=book.visible=b>0;card.position.set(2+(1-b)*5,1.85+(1-b)*.8,-.4);book.position.x=3.9+(1-b)*6;book.rotation.z=-.12+(1-b)*.35;renderer.render(scene,camera);frames++;}
 function resize(){if(dead)return;const r=host.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,1.25,1440/r.width,Math.sqrt(1000000/(r.width*r.height)));renderer.setPixelRatio(dpr);renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.fov=camera.aspect<1?49:34;camera.updateProjectionMatrix();}
 function dispose(){if(dead)return;dead=true;signal?.removeEventListener('abort',abort);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());environment.dispose();sun.shadow.dispose();renderer.renderLists.dispose();renderer.dispose();renderer.forceContextLoss();canvas.remove();}
 // Three polls shader completion asynchronously; remove immediately, dispose after its promise settles.
 const abort=()=>canvas.remove();signal?.addEventListener('abort',abort,{once:true});
 host.append(canvas);resize();try{await yieldUI();if(signal?.aborted||!host.isConnected){dispose();throw Error('Stage removed');}await renderer.compileAsync(scene,camera);await yieldUI();}catch(e){dispose();throw e;}if(!host.isConnected||signal?.aborted){dispose();throw Error('Stage removed');}return{canvas,render:(t)=>{render(t);canvas.style.visibility='visible';},resize,dispose,renderer,get info(){return{frames,triangles:renderer.info.render.triangles,calls:renderer.info.render.calls,buffer:[canvas.width,canvas.height],geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures}}};
}
